//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmDukkaniProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmKategori
    {
        public int FilmKategoriID { get; set; }
        public int KategoriID { get; set; }
        public int FilmID { get; set; }
    
        public virtual Filmler Filmler { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
