//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmDukkaniProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmler()
        {
            this.Film_Altyazi = new HashSet<Film_Altyazi>();
            this.FilmKategori = new HashSet<FilmKategori>();
            this.FilmListe = new HashSet<FilmListe>();
            this.Tedarik_Film = new HashSet<Tedarik_Film>();
        }
    
        public int FilmID { get; set; }
        public string FilmAdi { get; set; }
        public string Yonetmen { get; set; }
        public string Ozet { get; set; }
        public string Oyuncular { get; set; }
        public string YapimYili { get; set; }
        public string AldigiOduller { get; set; }
        public int BarkodNo { get; set; }
        public int Stok { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> TedarikciID { get; set; }
        public Nullable<int> AltYaziID { get; set; }
        public string Gorsel { get; set; }
    
        public virtual AltYazi AltYazi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film_Altyazi> Film_Altyazi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmKategori> FilmKategori { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmListe> FilmListe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tedarik_Film> Tedarik_Film { get; set; }
    }
}
