//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmDukkaniProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liste()
        {
            this.FilmListe = new HashSet<FilmListe>();
        }
    
        public int ListeID { get; set; }
        public Nullable<int> FilmID { get; set; }
        public Nullable<int> Oncelik { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string KullaniciUsername { get; set; }
        public Nullable<System.DateTime> KiralamaTarihi { get; set; }
        public Nullable<System.DateTime> GeriAlmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmListe> FilmListe { get; set; }
    }
}
