//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmDukkaniProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paket
    {
        public int PaketID { get; set; }
        public string PaketAdi { get; set; }
        public string Degisim { get; set; }
        public Nullable<int> FilmSayisi { get; set; }
        public Nullable<decimal> Ucret { get; set; }
    }
}
